# Generated by Django 4.2.1 on 2023-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_inventory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="sales",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=19, null=True
            ),
        ),
    ]
